-- =====================================
-- 01_regions_districts.sql
-- =====================================
CREATE TABLE region (
    region_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_name VARCHAR2(100) NOT NULL,
    region_code VARCHAR2(2) UNIQUE NOT NULL
);

CREATE TABLE district (
    district_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    district_name VARCHAR2(150) NOT NULL,
    district_type VARCHAR2(50),
    region_id INTEGER REFERENCES region(region_id)
);

CREATE TABLE sub_district (
    sub_district_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub_district_name VARCHAR2(150) NOT NULL,
    district_id INTEGER REFERENCES district(district_id)
);

-- =====================================
-- 02_enumeration.sql
-- =====================================
CREATE TABLE enumeration_area (
    ea_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ea_code VARCHAR2(20) UNIQUE NOT NULL,
    ea_type VARCHAR2(50),
    sub_district_id INTEGER REFERENCES sub_district(sub_district_id)
);

CREATE TABLE locality (
    locality_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    locality_name VARCHAR2(150) NOT NULL,
    locality_code VARCHAR2(20),
    ea_id INTEGER REFERENCES enumeration_area(ea_id)
);

-- =====================================
-- 03_staff.sql
-- =====================================
CREATE TABLE enumerator (
    enumerator_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enumerator_name VARCHAR2(150) NOT NULL,
    phone_number VARCHAR2(15),
    signature VARCHAR2(200),
    employee_id VARCHAR2(20) UNIQUE NOT NULL
);

CREATE TABLE supervisor (
    supervisor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supervisor_name VARCHAR2(150) NOT NULL,
    phone_number VARCHAR2(15),
    signature VARCHAR2(200),
    employee_id VARCHAR2(20) UNIQUE NOT NULL
);

-- =====================================
-- 04_housing.sql
-- =====================================
CREATE TABLE housing_unit (
    housing_unit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_number VARCHAR2(20),
    detailed_address CLOB,
    dwelling_type VARCHAR2(2),
    outer_wall_material VARCHAR2(2),
    roof_material VARCHAR2(2),
    floor_material VARCHAR2(2),
    ownership_type VARCHAR2(2),
    tenure_arrangement VARCHAR2(2),
    total_rooms INTEGER CHECK (total_rooms > 0),
    sleeping_rooms INTEGER CHECK (sleeping_rooms >= 0),
    shared_sleeping_room CHAR(1),
    households_sharing INTEGER CHECK (households_sharing >= 1),
    lighting_source VARCHAR2(2),
    drinking_water_source VARCHAR2(2),
    domestic_water_source VARCHAR2(2),
    cooking_fuel VARCHAR2(2),
    cooking_space_type VARCHAR2(2),
    bathing_facility VARCHAR2(2),
    toilet_facility VARCHAR2(2),
    shared_toilet VARCHAR2(2),
    households_using_toilet INTEGER CHECK (households_using_toilet >= 1),
    solid_waste_disposal VARCHAR2(2),
    liquid_waste_disposal VARCHAR2(2),
    locality_id INTEGER REFERENCES locality(locality_id)
);

-- =====================================
-- 05_household.sql
-- =====================================
CREATE TABLE household (
    household_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_number VARCHAR2(10),
    questionnaire_id VARCHAR2(20) UNIQUE,
    nis_ecg_vra_number VARCHAR2(50),
    contact_phone1 VARCHAR2(15),
    contact_phone2 VARCHAR2(15),
    date_started DATE,
    date_completed DATE,
    total_visits INTEGER CHECK (total_visits >= 1),
    form_number VARCHAR2(10),
    residence_type CHAR(1),
    occupied_members_male INTEGER CHECK (occupied_members_male >= 0),
    occupied_members_female INTEGER CHECK (occupied_members_female >= 0),
    visitor_members_male INTEGER CHECK (visitor_members_male >= 0),
    visitor_members_female INTEGER CHECK (visitor_members_female >= 0),
    absent_members_male INTEGER CHECK (absent_members_male >= 0),
    absent_members_female INTEGER CHECK (absent_members_female >= 0),
    total_status_ab_male INTEGER CHECK (total_status_ab_male >= 0),
    total_status_ab_female INTEGER CHECK (total_status_ab_female >= 0),
    has_fixed_phone CHAR(1),
    has_computer CHAR(1),
    has_deaths_past_12_months CHAR(1),
    engages_agriculture CHAR(1),
    male_farmers INTEGER CHECK (male_farmers >= 0),
    female_farmers INTEGER CHECK (female_farmers >= 0),
    housing_unit_id INTEGER REFERENCES housing_unit(housing_unit_id),
    enumerator_id INTEGER REFERENCES enumerator(enumerator_id),
    supervisor_id INTEGER REFERENCES supervisor(supervisor_id)
);

-- =====================================
-- 06_person.sql
-- =====================================
CREATE TABLE person (
    person_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_line_number VARCHAR2(2),
    full_name VARCHAR2(300),
    relationship_to_head VARCHAR2(2),
    sex CHAR(1),
    member_status CHAR(1),
    date_of_birth DATE,
    age INTEGER CHECK (age >= 0 AND age <= 150),
    nationality VARCHAR2(2),
    ethnicity VARCHAR2(5),
    born_in_current_location CHAR(1),
    birthplace_region_country VARCHAR2(2),
    lived_here_since_birth CHAR(1),
    years_in_current_location INTEGER CHECK (years_in_current_location >= 0),
    religion VARCHAR2(2),
    marital_status VARCHAR2(2),
    literacy_languages VARCHAR2(2),
    ever_attended_school VARCHAR2(2),
    highest_education_level VARCHAR2(2),
    highest_grade_completed INTEGER CHECK (highest_grade_completed >= 0),
    owns_mobile_phone CHAR(1),
    uses_internet CHAR(1),
    children_ever_born_male INTEGER CHECK (children_ever_born_male >= 0),
    children_ever_born_female INTEGER CHECK (children_ever_born_female >= 0),
    children_surviving_male INTEGER CHECK (children_surviving_male >= 0),
    children_surviving_female INTEGER CHECK (children_surviving_female >= 0),
    children_born_past_12_months_male INTEGER CHECK (children_born_past_12_months_male >= 0),
    children_born_past_12_months_female INTEGER CHECK (children_born_past_12_months_female >= 0),
    household_id INTEGER REFERENCES household(household_id)
);

-- =====================================
-- 07_employment_disability.sql
-- =====================================
CREATE TABLE employment (
    employment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worked_past_7_days CHAR(1),
    main_engagement VARCHAR2(2),
    no_work_reason VARCHAR2(2),
    occupation_code VARCHAR2(4),
    occupation_description CLOB,
    establishment_name VARCHAR2(300),
    establishment_location VARCHAR2(300),
    industry_code VARCHAR2(4),
    industry_description CLOB,
    employment_status VARCHAR2(2),
    employment_sector VARCHAR2(2),
    person_id INTEGER UNIQUE REFERENCES person(person_id)
);

CREATE TABLE disability (
    disability_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    has_sight_disability CHAR(1),
    has_hearing_disability CHAR(1),
    has_speech_disability CHAR(1),
    has_physical_disability CHAR(1),
    has_intellectual_disability CHAR(1),
    has_emotional_disability CHAR(1),
    has_other_disability CHAR(1),
    other_disability_description VARCHAR2(300),
    person_id INTEGER UNIQUE REFERENCES person(person_id)
);

-- =====================================
-- 08_mortality_absence.sql
-- =====================================
CREATE TABLE absent_member (
    absent_member_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_number VARCHAR2(2),
    full_name VARCHAR2(300),
    relationship_to_head VARCHAR2(2),
    sex CHAR(1),
    age INTEGER CHECK (age >= 0 AND age <= 150),
    destination_town VARCHAR2(150),
    destination_region_country VARCHAR2(2),
    months_absent INTEGER CHECK (months_absent >= 0),
    household_id INTEGER REFERENCES household(household_id)
);

CREATE TABLE emigrant (
    emigrant_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_number VARCHAR2(2),
    full_name VARCHAR2(300),
    age INTEGER CHECK (age >= 15 AND age <= 150),
    year_departure INTEGER,
    activity_abroad VARCHAR2(2),
    activity_abroad_other VARCHAR2(300),
    country_code VARCHAR2(3),
    relationship_to_head VARCHAR2(2),
    sex CHAR(1),
    household_id INTEGER REFERENCES household(household_id)
);

CREATE TABLE mortality_record (
    mortality_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_number VARCHAR2(2),
    deceased_name VARCHAR2(300),
    sex CHAR(1),
    age_at_death INTEGER CHECK (age_at_death >= 0 AND age_at_death <= 150),
    death_due_to_violence CHAR(1),
    maternal_death CHAR(1),
    household_id INTEGER REFERENCES household(household_id)
);

-- =====================================
-- 09_agriculture.sql
-- =====================================
CREATE TABLE agricultural_activity (
    activity_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    engages_crop_farming CHAR(1),
    engages_tree_growing CHAR(1),
    engages_livestock_rearing CHAR(1),
    engages_fish_farming CHAR(1),
    household_id INTEGER UNIQUE REFERENCES household(household_id)
);

CREATE TABLE crop_farming (
    crop_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_number VARCHAR2(2),
    crop_type VARCHAR2(300),
    crop_code VARCHAR2(4),
    farm_size NUMBER(12,4),
    measurement_unit VARCHAR2(2),
    cropping_type VARCHAR2(2),
    activity_id INTEGER REFERENCES agricultural_activity(activity_id)
);

CREATE TABLE livestock_farming (
    livestock_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_number VARCHAR2(2),
    livestock_type VARCHAR2(300),
    livestock_code VARCHAR2(4),
    number_owned INTEGER CHECK (number_owned >= 0),
    activity_id INTEGER REFERENCES agricultural_activity(activity_id)
);

