-- =====================================
-- USER ACTIVITY LOGGING TRIGGERS
-- =====================================

-- Create user activity log table
CREATE TABLE user_activity_log (
  log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name VARCHAR2(50) NOT NULL,
  operation VARCHAR2(10) NOT NULL,
  record_id NUMBER,
  old_values CLOB,
  new_values CLOB,
  user_id VARCHAR2(50) DEFAULT 'SYSTEM',
  timestamp TIMESTAMP DEFAULT SYSTIMESTAMP,
  ip_address VARCHAR2(45)
);

-- Create sequence for log IDs
CREATE SEQUENCE log_seq START WITH 1 INCREMENT BY 1;

-- =====================================
-- REGION TRIGGERS
-- =====================================

-- Trigger for logging region operations
CREATE OR REPLACE TRIGGER region_audit_trigger
AFTER INSERT OR UPDATE OR DELETE ON region
FOR EACH ROW
DECLARE
  v_operation VARCHAR2(10);
  v_old_values CLOB;
  v_new_values CLOB;
BEGIN
  IF INSERTING THEN
    v_operation := 'INSERT';
    v_new_values := '{"region_id":' || :NEW.region_id || 
                   ',"region_name":"' || :NEW.region_name || 
                   '","region_code":"' || :NEW.region_code || '"}';
  ELSIF UPDATING THEN
    v_operation := 'UPDATE';
    v_old_values := '{"region_id":' || :OLD.region_id || 
                   ',"region_name":"' || :OLD.region_name || 
                   '","region_code":"' || :OLD.region_code || '"}';
    v_new_values := '{"region_id":' || :NEW.region_id || 
                   ',"region_name":"' || :NEW.region_name || 
                   '","region_code":"' || :NEW.region_code || '"}';
  ELSIF DELETING THEN
    v_operation := 'DELETE';
    v_old_values := '{"region_id":' || :OLD.region_id || 
                   ',"region_name":"' || :OLD.region_name || 
                   ',"region_code":"' || :OLD.region_code || '"}';
  END IF;

  INSERT INTO user_activity_log (log_id, table_name, operation, record_id, old_values, new_values)
  VALUES (log_seq.NEXTVAL, 'REGION', v_operation, 
          CASE WHEN INSERTING THEN :NEW.region_id ELSE :OLD.region_id END,
          v_old_values, v_new_values);
END;
/

-- =====================================
-- DISTRICT TRIGGERS
-- =====================================

-- Trigger for logging district operations
CREATE OR REPLACE TRIGGER district_audit_trigger
AFTER INSERT OR UPDATE OR DELETE ON district
FOR EACH ROW
DECLARE
  v_operation VARCHAR2(10);
  v_old_values CLOB;
  v_new_values CLOB;
BEGIN
  IF INSERTING THEN
    v_operation := 'INSERT';
    v_new_values := '{"district_id":' || :NEW.district_id || 
                   ',"district_name":"' || :NEW.district_name || 
                   '","district_type":"' || :NEW.district_type || 
                   '","region_id":' || :NEW.region_id || '}';
  ELSIF UPDATING THEN
    v_operation := 'UPDATE';
    v_old_values := '{"district_id":' || :OLD.district_id || 
                   ',"district_name":"' || :OLD.district_name || 
                   ',"district_type":"' || :OLD.district_type || 
                   ',"region_id":' || :OLD.region_id || '}';
    v_new_values := '{"district_id":' || :NEW.district_id || 
                   ',"district_name":"' || :NEW.district_name || 
                   ',"district_type":"' || :NEW.district_type || 
                   ',"region_id":' || :NEW.region_id || '}';
  ELSIF DELETING THEN
    v_operation := 'DELETE';
    v_old_values := '{"district_id":' || :OLD.district_id || 
                   ',"district_name":"' || :OLD.district_name || 
                   ',"district_type":"' || :OLD.district_type || 
                   ',"region_id":' || :OLD.region_id || '}';
  END IF;

  INSERT INTO user_activity_log (log_id, table_name, operation, record_id, old_values, new_values)
  VALUES (log_seq.NEXTVAL, 'DISTRICT', v_operation, 
          CASE WHEN INSERTING THEN :NEW.district_id ELSE :OLD.district_id END,
          v_old_values, v_new_values);
END;
/

-- =====================================
-- ENUMERATOR TRIGGERS
-- =====================================

-- Trigger for logging enumerator operations
CREATE OR REPLACE TRIGGER enumerator_audit_trigger
AFTER INSERT OR UPDATE OR DELETE ON enumerator
FOR EACH ROW
DECLARE
  v_operation VARCHAR2(10);
  v_old_values CLOB;
  v_new_values CLOB;
BEGIN
  IF INSERTING THEN
    v_operation := 'INSERT';
    v_new_values := '{"enumerator_id":' || :NEW.enumerator_id || 
                   ',"enumerator_name":"' || :NEW.enumerator_name || 
                   ',"phone_number":"' || :NEW.phone_number || 
                   ',"employee_id":"' || :NEW.employee_id || '"}';
  ELSIF UPDATING THEN
    v_operation := 'UPDATE';
    v_old_values := '{"enumerator_id":' || :OLD.enumerator_id || 
                   ',"enumerator_name":"' || :OLD.enumerator_name || 
                   ',"phone_number":"' || :OLD.phone_number || 
                   ',"employee_id":"' || :OLD.employee_id || '"}';
    v_new_values := '{"enumerator_id":' || :NEW.enumerator_id || 
                   ',"enumerator_name":"' || :NEW.enumerator_name || 
                   ',"phone_number":"' || :NEW.phone_number || 
                   ',"employee_id":"' || :NEW.employee_id || '"}';
  ELSIF DELETING THEN
    v_operation := 'DELETE';
    v_old_values := '{"enumerator_id":' || :OLD.enumerator_id || 
                   ',"enumerator_name":"' || :OLD.enumerator_name || 
                   ',"phone_number":"' || :OLD.phone_number || 
                   ',"employee_id":"' || :OLD.employee_id || '"}';
  END IF;

  INSERT INTO user_activity_log (log_id, table_name, operation, record_id, old_values, new_values)
  VALUES (log_seq.NEXTVAL, 'ENUMERATOR', v_operation, 
          CASE WHEN INSERTING THEN :NEW.enumerator_id ELSE :OLD.enumerator_id END,
          v_old_values, v_new_values);
END;
/

-- =====================================
-- SUPERVISOR TRIGGERS
-- =====================================

-- Trigger for logging supervisor operations
CREATE OR REPLACE TRIGGER supervisor_audit_trigger
AFTER INSERT OR UPDATE OR DELETE ON supervisor
FOR EACH ROW
DECLARE
  v_operation VARCHAR2(10);
  v_old_values CLOB;
  v_new_values CLOB;
BEGIN
  IF INSERTING THEN
    v_operation := 'INSERT';
    v_new_values := '{"supervisor_id":' || :NEW.supervisor_id || 
                   ',"supervisor_name":"' || :NEW.supervisor_name || 
                   ',"phone_number":"' || :NEW.phone_number || 
                   ',"employee_id":"' || :NEW.employee_id || '"}';
  ELSIF UPDATING THEN
    v_operation := 'UPDATE';
    v_old_values := '{"supervisor_id":' || :OLD.supervisor_id || 
                   ',"supervisor_name":"' || :OLD.supervisor_name || 
                   ',"phone_number":"' || :OLD.phone_number || 
                   ',"employee_id":"' || :OLD.employee_id || '"}';
    v_new_values := '{"supervisor_id":' || :NEW.supervisor_id || 
                   ',"supervisor_name":"' || :NEW.supervisor_name || 
                   ',"phone_number":"' || :NEW.phone_number || 
                   ',"employee_id":"' || :NEW.employee_id || '"}';
  ELSIF DELETING THEN
    v_operation := 'DELETE';
    v_old_values := '{"supervisor_id":' || :OLD.supervisor_id || 
                   ',"supervisor_name":"' || :OLD.supervisor_name || 
                   ',"phone_number":"' || :OLD.phone_number || 
                   ',"employee_id":"' || :OLD.employee_id || '"}';
  END IF;

  INSERT INTO user_activity_log (log_id, table_name, operation, record_id, old_values, new_values)
  VALUES (log_seq.NEXTVAL, 'SUPERVISOR', v_operation, 
          CASE WHEN INSERTING THEN :NEW.supervisor_id ELSE :OLD.supervisor_id END,
          v_old_values, v_new_values);
END;
/

-- =====================================
-- HOUSEHOLD TRIGGERS
-- =====================================

-- Trigger for logging household operations
CREATE OR REPLACE TRIGGER household_audit_trigger
AFTER INSERT OR UPDATE OR DELETE ON household
FOR EACH ROW
DECLARE
  v_operation VARCHAR2(10);
  v_old_values CLOB;
  v_new_values CLOB;
BEGIN
  IF INSERTING THEN
    v_operation := 'INSERT';
    v_new_values := '{"household_id":' || :NEW.household_id || 
                   ',"household_number":"' || :NEW.household_number || 
                   ',"questionnaire_id":"' || :NEW.questionnaire_id || 
                   ',"contact_phone1":"' || :NEW.contact_phone1 || 
                   '","occupied_members_male":' || :NEW.occupied_members_male || 
                   ',"occupied_members_female":' || :NEW.occupied_members_female || '}';
  ELSIF UPDATING THEN
    v_operation := 'UPDATE';
    v_old_values := '{"household_id":' || :OLD.household_id || 
                   ',"household_number":"' || :OLD.household_number || 
                   ',"questionnaire_id":"' || :OLD.questionnaire_id || 
                   ',"contact_phone1":"' || :OLD.contact_phone1 || 
                   '","occupied_members_male":' || :OLD.occupied_members_male || 
                   ',"occupied_members_female":' || :OLD.occupied_members_female || '}';
    v_new_values := '{"household_id":' || :NEW.household_id || 
                   ',"household_number":"' || :NEW.household_number || 
                   ',"questionnaire_id":"' || :NEW.questionnaire_id || 
                   ',"contact_phone1":"' || :NEW.contact_phone1 || 
                   '","occupied_members_male":' || :NEW.occupied_members_male || 
                   ',"occupied_members_female":' || :NEW.occupied_members_female || '}';
  ELSIF DELETING THEN
    v_operation := 'DELETE';
    v_old_values := '{"household_id":' || :OLD.household_id || 
                   ',"household_number":"' || :OLD.household_number || 
                   ',"questionnaire_id":"' || :OLD.questionnaire_id || 
                   ',"contact_phone1":"' || :OLD.contact_phone1 || 
                   '","occupied_members_male":' || :OLD.occupied_members_male || 
                   ',"occupied_members_female":' || :OLD.occupied_members_female || '}';
  END IF;

  INSERT INTO user_activity_log (log_id, table_name, operation, record_id, old_values, new_values)
  VALUES (log_seq.NEXTVAL, 'HOUSEHOLD', v_operation, 
          CASE WHEN INSERTING THEN :NEW.household_id ELSE :OLD.household_id END,
          v_old_values, v_new_values);
END;
/

-- =====================================
-- PERSON TRIGGERS
-- =====================================

-- Trigger for logging person operations
CREATE OR REPLACE TRIGGER person_audit_trigger
AFTER INSERT OR UPDATE OR DELETE ON person
FOR EACH ROW
DECLARE
  v_operation VARCHAR2(10);
  v_old_values CLOB;
  v_new_values CLOB;
BEGIN
  IF INSERTING THEN
    v_operation := 'INSERT';
    v_new_values := '{"person_id":' || :NEW.person_id || 
                   ',"full_name":"' || :NEW.full_name || 
                   ',"sex":"' || :NEW.sex || 
                   '","age":' || :NEW.age || 
                   ',"household_id":' || :NEW.household_id || '}';
  ELSIF UPDATING THEN
    v_operation := 'UPDATE';
    v_old_values := '{"person_id":' || :OLD.person_id || 
                   ',"full_name":"' || :OLD.full_name || 
                   ',"sex":"' || :OLD.sex || 
                   '","age":' || :OLD.age || 
                   ',"household_id":' || :OLD.household_id || '}';
    v_new_values := '{"person_id":' || :NEW.person_id || 
                   ',"full_name":"' || :NEW.full_name || 
                   ',"sex":"' || :NEW.sex || 
                   '","age":' || :NEW.age || 
                   ',"household_id":' || :NEW.household_id || '}';
  ELSIF DELETING THEN
    v_operation := 'DELETE';
    v_old_values := '{"person_id":' || :OLD.person_id || 
                   ',"full_name":"' || :OLD.full_name || 
                   ',"sex":"' || :OLD.sex || 
                   '","age":' || :OLD.age || 
                   ',"household_id":' || :OLD.household_id || '}';
  END IF;

  INSERT INTO user_activity_log (log_id, table_name, operation, record_id, old_values, new_values)
  VALUES (log_seq.NEXTVAL, 'PERSON', v_operation, 
          CASE WHEN INSERTING THEN :NEW.person_id ELSE :OLD.person_id END,
          v_old_values, v_new_values);
END;
/ 