
-- =====================================
-- 12_drop_all_tables.sql (For reset/testing)
-- =====================================
-- Drop in reverse order to avoid FK errors
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE livestock_farming CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE crop_farming CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE agricultural_activity CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE mortality_record CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE emigrant CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE absent_member CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE disability CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE employment CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE person CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE household CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE housing_unit CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE supervisor CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE enumerator CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE locality CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE enumeration_area CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE sub_district CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE district CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE region CASCADE CONSTRAINTS';
END;
/
